{% set name = "traefik" %}
{% set version = "2.10.7" %}
{% set gomodule = "github.com/traefik/" ~ name %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: src/{{ gomodule }}
    url: https://{{ gomodule }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.src.tar.gz
    sha256: 64f8fdcb907b8f6cd7431cf91607f45b576324bf224efe4ea0f3dc09e65db6a6

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses

test:
  commands:
    - traefik version
    - traefik version | grep -iE  "Version:\s+{{ version.replace(".", "\.") }}$"
    - traefik --help

about:
  home: https://traefik.io
  license: MIT
  license_file:
    - src/{{ gomodule }}/LICENSE.md
    - library_licenses/

  summary: The Cloud Native Application Proxy

  description: |
    Traefik (pronounced traffic) is a modern HTTP reverse proxy and load balancer
    that makes deploying microservices easy. Traefik integrates with your existing
    infrastructure components (Docker, Swarm mode, Kubernetes, Consul, Etcd,
    Rancher v2, Amazon ECS, ...) and configures itself automatically and dynamically.
    Pointing Traefik at your orchestrator should be the only configuration step you need.

  doc_url: https://doc.traefik.io/traefik
  dev_url: https://{{ gomodule }}

extra:
  recipe-maintainers:
    - bollwyvl
