{% set min_go = ">=1.19" %}
{% set name = "traefik" %}
{% set version = "2.10.3" %}
{% set gomodule = "github.com/traefik/" ~ name %}
{% set min_go = ">=1.19" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: src/{{ gomodule }}
    url: https://{{ gomodule }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.src.tar.gz
    sha256: eb4694ef72a8356a2acf36315e5e141027001c1eef8acade7ecb86512305d286

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - go {{ min_go }}
    - go-licenses

test:
  commands:
    - traefik version
    - traefik version | grep -iE  "Version:\s+{{ version.replace(".", "\.") }}$"
    - traefik --help

about:
  home: https://traefik.io
  license: MIT
  license_file:
    - src/{{ gomodule }}/LICENSE.md
    - library_licenses/

  summary: The Cloud Native Application Proxy

  description: |
    Traefik (pronounced traffic) is a modern HTTP reverse proxy and load balancer
    that makes deploying microservices easy. Traefik integrates with your existing
    infrastructure components (Docker, Swarm mode, Kubernetes, Consul, Etcd,
    Rancher v2, Amazon ECS, ...) and configures itself automatically and dynamically.
    Pointing Traefik at your orchestrator should be the only configuration step you need.

  doc_url: https://doc.traefik.io/traefik
  dev_url: https://{{ gomodule }}

extra:
  recipe-maintainers:
    - bollwyvl
